apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loan-prediction-api
  namespace: user-oualy
spec:
  project: default

  source:
    repoURL: https://github.com/kellybourbon2/Loan-prediction-approval
    targetRevision: ossama
    path: k8s
    # Exclude the ArgoCD app manifest itself and secret template
    directory:
      exclude: "argocd-app.yaml,secret.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: user-oualy

  syncPolicy:
    automated:
      prune: true      # remove resources deleted from git
      selfHeal: true   # revert manual changes on the cluster
    syncOptions:
      - ServerSideApply=true
