name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # 3. Install uv
      - name: Install uv
        run: pip install uv

      # 4. Install dependencies
      - name: Install dependencies
        run: uv sync --dev

      # 5. Run linting
      - name: Run flake8
        run: uv run flake8 .

      # 6. Run isort
      - name: Run isort
        run: uv run isort .

      # 7. Run formatting check
      - name: Check formatting with black
        run: uv run black --check .

      # # 8. Run tests
      # - name: Run tests
      #   run: uv run pytest

      # # 9. Run training script 
      # - name: Train model
      #   run: uv run python src/train.py